### ISSUE TITLE
HDFSFileSourceTxtFormat sample does not run due to conversion error

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.hdfs#90]
Using 4.2 QSE to run that sample, I get this error:

```
Exception in thread "Thread-19" java.lang.RuntimeException: java.lang.Exception: The conversion from the This is tuple number 0 string to a C++ type of SPL::BeJwrMc80ykwpNk3LS8xNLTbNAVGZxonpqcVm6al5KalFaabFyflFqW6mJfkliTkAorcRC1 did not succeed.
	at com.ibm.streamsx.hdfs.AbstractHdfsOperator$1.run(AbstractHdfsOperator.java:101)
	at java.lang.Thread.run(Thread.java:785)
	at 
```
I think it has something to do with this portion of code:
		

```stream<PersonSchema> tupleValue = Custom(LineStream)
		{
			logic
				onTuple LineStream : submit((tuple<PersonSchema>) LineStream.lines,
					tupleValue) ;
		}
```

**Comment by anouri** [comment]
Correction will be delivered in HDFS toolkit version 4.2.0

**Comment by anouri** [comment]
The correction has been delivered in HDFS toolkit version 4.2.0
